### ISSUE TITLE
RE: Export (MAL) option unable to find/update MAL entries

### ISSUE THREAD

**Issue by thaminc** [Glagan/MyMangaDex#19]
I'm having a similar problem to user awwang previously solved in exporting my fav list from MD to MAL. Reading chapters on MD adds chapters on MAL as usual. Anything I can attempt differently? 
Should I wait until MD moves back to .org?

**Comment by Glagan** [comment]
I see why this isn't working, I will fix it.

**Comment by Glagan** [comment]
It should be fixed, tell me if you have any other problem ;)

**Comment by thaminc** [comment]
Will attempt again, thank you!

**Comment by thaminc** [comment]
2nd attempt still having the same issue, will attempt once more

**Comment by thaminc** [comment]
Working now, thank you! :)
